### ISSUE TITLE
阴影的坐标计算的不对，应该需要转换成屏幕坐标。录制的视频如下

### ISSUE THREAD

**Issue by csh159** [wangguifa/paper#1]
[录制视频.zip](https://github.com/wangguifa/paper/files/4625744/default.zip)

**Comment by csh159** [comment]
points 感觉是请求接口的时候给屏幕的大小计算出来的

**Comment by wangguifa** [comment]
> points 感觉是请求接口的时候给屏幕的大小计算出来的

坐标是服务器计算并返回给客户端的
